### ISSUE TITLE
センサーの設置に関して

### ISSUE THREAD

**Issue by ShuftBK** [ShuftBK/Arduino-IlluminationPulseSensor#1]
早急にセンサー設置用の看板とかの設計をしないといけないｱﾚ  
- 屋外用の灰皿の高さと斜形の形がすごくいい感じではある
- ｱﾚをそのまま作れるとは言えないし、看板のように柱につけられるようにしないといけない

**Comment by ShuftBK** [comment]
零月、あとは頼んだ(ここで通信は途切れている

**Comment by luna01926** [comment]
つよくいきて

**Comment by ShuftBK** [comment]
いい感じになりましたのでclose
